repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: black
  - id: flake8
  - id: isort
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.7.1
  hooks:
  - id: prettier
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.12.0
  hooks:
  - id: eslint
- repo: https://github.com/pre-commit/mirrors-nextjs
  rev: v3.1.0
  hooks:
  - id: nextjs
- repo: https://github.com/pre-commit/mirrors-nodemon
  rev: v2.0.15
  hooks:
  - id: nodemon
- repo: https://github.com/pre-commit/mirrors-stylelint
  rev: v14.10.0
  hooks:
  - id: stylelint